security:

    encoders:
      App\Entity\User:
        algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
      entity_provider:
        entity:
          class: App\Entity\User
          property: name

    firewalls:
      dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
      login:
        pattern:  ^/login
        stateless: true
        anonymous: true
        provider: entity_provider
        form_login:
          check_path: /login_check
          provider: entity_provider
          username_parameter : username
          password_parameter : password
          success_handler:          lexik_jwt_authentication.handler.authentication_success
          failure_handler:          lexik_jwt_authentication.handler.authentication_failure
          require_previous_session: false

      newuser:
        pattern:  ^/newuser
        stateless: true
        anonymous: true

      api:
        pattern:  ^/api
        stateless: true
        anonymous: false
        guard:
          provider: entity_provider
          authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
      main:
        anonymous: true

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/newuser, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }